### ISSUE TITLE
The birth process of "NEU_train_files.csv"and other documents

### ISSUE THREAD

**Issue by FENGJIANJUN99** [djene-mengistu/dseg_models#1]
Dear author:
        I downloaded the NEU Seg dataset, but its files only contain images and corresponding label images. The files you provided, such as "NEU_train_files. csv," contain detailed information on "ImageId_ ClassId" and EncodedPixels are parameters. How are these parameters generated and what do they represent? Looking forward to your reply!

**Comment by djene-mengistu** [comment]
Dear researcher(@FENGJIANJUN99 ):
Thank you for showing interest in our work. The training images in the SSDD dataset are provided with images and  corresponding masks in rle (run-length-encoding) of the location of defects in the image in .CSV format. To follow the same format with this dataset, I converted the annotation of each image in the NEU dataset to rle as well. However, you can just just prepare your own data loader using the images and annotations provided in the dataset.

**Comment by FENGJIANJUN99** [comment]
> Dear researcher(@FENGJIANJUN99 ): Thank you for showing interest in our work. The training images in the SSDD dataset are provided with images and corresponding masks in rle (run-length-encoding) of the location of defects in the image in .CSV format. To follow the same format with this dataset, I converted the annotation of each image in the NEU dataset to rle as well. However, you can just just prepare your own data loader using the images and annotations provided in the dataset.

Thank you very much for answering my questions!
