### ISSUE TITLE
About setting num_classes in the SSDD dataset

### ISSUE THREAD

**Issue by entuo** [djene-mengistu/dseg_models#2]
Congratulations!
    You have achieved amazing results on the SSDD dataset. However, there are some questions that I hope to get your answer for. The SSDD dataset has 4 defect classes, and with the background included, the num_classes should be set as 5. Why did you set it to 4 in your code?
     Looking forward to your reply.

**Comment by djene-mengistu** [comment]
@entuo Thank you for you interest in our work. It is true that the number of defects in the dataset is 4 and it should be 5 including background. However, in my implementation, I have used Sigmoid with binary-cross-entropy (BCE). As a result the focus is on identifying whether a given defect class exists in an image or not. For your case, if you train your network using multi-class segmentation using cross-entropy you can accordingly modify the number of classes.

**Comment by entuo** [comment]
Thank you for your response，which nicely answers my question. At the same time, I also noticed that you have commented on many augmentation methods in data augmentation. Have you adopted those commented augmentation methods to enhance the SSDD dataset? I look forward to your reply and wish you a wonderful day.

**Comment by djene-mengistu** [comment]
> Thank you for your response，which nicely answers my question. At the same time, I also noticed that you have commented on many augmentation methods in data augmentation. Have you adopted those commented augmentation methods to enhance the SSDD dataset? I look forward to your reply and wish you a wonderful day.

Several augmentations have been experimented and only the uncommented {HF, Blur, and Gaussian Noise} are used throughout the experiments. You can however try including other augmentations, make sure that the input dimension (256x1600 in my implementation) is not affected when you apply augmentations such as cropping.

**Comment by entuo** [comment]
Thank you for your response.

**Comment by entuo** [comment]
I'm sorry to bother you again. Could you please explain how you used BCE_loss in your article? How does it work, and how did you use it to perform defect classification and identification? Is this method comparable in effectiveness to CE_loss? I would appreciate your response.
